### ISSUE TITLE
Option to disable Unlock

### ISSUE THREAD

**Issue by idominiki** [ts1/BLEUnlock#10]
Would be great If I can disable the unlock option like the lock option. 

Thanks for your work!

**Comment by ts1** [comment]
@idominiki I'll add this option when I have time.

**Comment by ts1** [comment]
Done.

**Comment by timmerk** [comment]
I saw you did this in the latest release - thank you!

**Comment by idominiki** [comment]
Hey @ts1 
even If I disable the unlock, BLEunlock want to enter a password in login screen. If no password is set, it shows a message that no password is set after login.

Can look at this or help?

Thanks and Greets
<img width="146" alt="Bildschirmfoto 2020-04-18 um 15 13 23" src="https://user-images.githubusercontent.com/62521486/79638735-65ff0000-8187-11ea-9d41-b426144162a7.png">

**Comment by ts1** [comment]
@idominiki 
I'll fix it soon.
