### ISSUE TITLE
My device is not visible 

### ISSUE THREAD

**Issue by krushnadeore** [ts1/BLEUnlock#101]
Android : Poco X4 5g
MacBook Air M1 : macOS Monterey 12.6.7
Mac address is static still my device is not visible in device list 
I tried all options like passive mode and others
even I am able to connect my phone to Mac bluetooth and transfer file still device is not visible in BLEunlock app 
Or is there any way I can add key inside .plist file by converting my phones Mac address ?

**Comment by tryfunds-admin** [comment]
My Android (OPPO Reno5 A, Android 12) is not visible either. ☹️
It's visible in System Preferences.
I guess recent Android is not compatible to Apple's CoreBluetooth.
It's not possible to manually insert because it needs UUID, not MAC address.

**Comment by ts1** [comment]
My Android (OPPO Reno5 A, Android 12) is not visible either. ☹️
It's visible in System Preferences.
I guess recent Android is not compatible with CoreBluetooth.
It's not possible to add it manually because it needs UUID that is created by CoreBluetooth.
