### ISSUE TITLE
Cannot unlock mac on macOS14 Sonoma

### ISSUE THREAD

**Issue by lightumcc** [ts1/BLEUnlock#103]
It can only display the TouchID, but no password input frame
![9921692844671_ pic](https://github.com/ts1/BLEUnlock/assets/60721270/c47e61ab-cf62-4eb6-889c-734c03a63d82)

**Comment by TomatoFryEggs** [comment]
重选下设备就好了

**Comment by ts1** [comment]
Hey there! I can't seem to reproduce this bug on my end. If you're experiencing it, could you please provide more details about your environment? It might help narrow things down. Thanks! 😊

**Comment by QuantumRoseinAmethystVase** [comment]
This has nothing to do with BLEUnlock. By default, Mac hides the password input box when waking up the screen, and it appears after a single click on the screen.

**Comment by bren0524** [comment]
Same problem appeared after I update both my macmini and  macbook air to sonoma,bleunlock cant unlock my sonoma system.
