### ISSUE TITLE
can't find device when my phone stop scanning

### ISSUE THREAD

**Issue by hainingfang** [ts1/BLEUnlock#105]
My Mac can find my phone(Samsung s23u) only when I manually start Bluetooth scanning on my phone, Mac lost the device immediately after the phone stopped scanning. How to make the connection continue?

**Comment by ts1** [comment]
Recent versions of Android don't work very well with BLEUnlock. Please refer to https://github.com/ts1/BLEUnlock#notes-on-mac-address for more information.
