### ISSUE TITLE
 someone has plagiarized your software

### ISSUE THREAD

**Issue by macoswk** [ts1/BLEUnlock#115]
It seems that someone has plagiarized your software,Or maybe I misunderstood
<img width="1323" alt="截屏2024-01-28 14 44 18" src="https://github.com/ts1/BLEUnlock/assets/86730293/1e4edb33-6e0d-4f63-8cb8-14362cc04fab">

**Comment by ts1** [comment]
Indeed, it seems so. Thank you for telling me.
