### ISSUE TITLE
how can i find which is my device

### ISSUE THREAD

**Issue by arjing** [ts1/BLEUnlock#12]
![image](https://user-images.githubusercontent.com/10625324/82518869-e16f1b00-9b52-11ea-80ac-f04b86eb1a4e.png)

**Comment by ts1** [comment]
Raise minimum RSSI to -60 or so and keep your device close to Mac.
Most probably the one with highest RSSI is your device.

**Comment by chenrylee** [comment]
@ts1 Actually not, here's a test:
I put 2 iPhones (iPhone XR and iPhone 6S Plus) near my laptop, XR is tightly close to my laptop(0mm), and 6SP is about 1 meter, but the RSSI of 6SP(-36dBm) is higher than the XR (-44dBm).

**Comment by ts1** [comment]
@arjing Please try https://github.com/ts1/BLEUnlock/releases/tag/v1.9.0-beta
It should display Bluetooth device name.

**Comment by ts1** [comment]
@chenrylee it may be because transmitting signal strength is different per device.
Anyways, in version 1.9.0 it displays Bluetooth name and MAC address of devices.
I believe this fixed the issue.
Feel free to reopen if you still have problems.
