### ISSUE TITLE
Remove RSSI restrictions for unlocking and locking

### ISSUE THREAD

**Issue by linluoran** [ts1/BLEUnlock#127]
Lock and unlock are two separate actions, I want to lock immediately when I leave and unlock before I come back, but there seems to be a limit to setting the unlock value higher than the lock value.

**Comment by ts1** [comment]
You can certainly set the RSSI values for lock and unlock to be the same. However, if you set the unlock value lower than the lock value, it can create uncertainty about whether to lock or unlock when the RSSI is between these two values. That's why it is designed this way.
