### ISSUE TITLE
Alternative app for Windows

### ISSUE THREAD

**Issue by L1cardo** [ts1/BLEUnlock#14]
Do anybody know is there a similar app for Windows that I can unlock my pc with Bluetooth devices?

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by chenrylee** [comment]
On Windows, I use dynamic lock and Windows Hello.
Pair my phone with Windows, and if I leave my seat, my laptop will be locked;
when I'm back to my seat, and the camera recognizes me, my laptop will be unlocked.

**Comment by ts1** [comment]
I close this issue because it's off-topic.
