### ISSUE TITLE
Disable universal clipboard and relay

### ISSUE THREAD

**Issue by WentaoHao** [ts1/BLEUnlock#15]
This software will disable universal clipboard from the Mac to the iPad. Both the Relay is. They work well when this software is turned off.

**Comment by ts1** [comment]
It works with my iPhone.
Can you try to enable Passive Mode of BLEUnlock?

**Comment by WentaoHao** [comment]
The passive mode works better. I tested about ten times. After one time it failed, I restarted the software and tested again, it all worked normally and the problem is not reproduced. I am very grateful for such good software. : )
