### ISSUE TITLE
Display Bluetooth name instead of device name

### ISSUE THREAD

**Issue by VFiee** [ts1/BLEUnlock#17]
My device is Iphone xs. There are multiple people in the company who use Iphone xs. In order to avoid the wrong choice, I modified my Bluetooth name. However, when I search for the device again, I cannot find my device (the modified Bluetooth name, even though 
You can check the distance through dBm, but it is usually easy to confuse), so if you modify it to display according to the Bluetooth name, it will be very helpful to people like me, thank you!

**Comment by ts1** [comment]
I found a way.
This feature will be released shortly!

**Comment by ts1** [comment]
@VFiee Please try https://github.com/ts1/BLEUnlock/releases/tag/v1.9.0-beta

**Comment by VFiee** [comment]
> @VFiee Please try https://github.com/ts1/BLEUnlock/releases/tag/v1.9.0-beta
Okay, I'll try it later and give you feedback. thank you!

**Comment by VFiee** [comment]
> > @VFiee Please try https://github.com/ts1/BLEUnlock/releases/tag/v1.9.0-beta
> > Okay, I'll try it later and give you feedback. thank you!

It seems that the expected behavior does not occur (the Bluetooth name is displayed)!
Show a few pictures,
![mac](https://user-images.githubusercontent.com/42051272/93665835-393f7380-faac-11ea-9b79-a40ef9876a30.png)
![phone2](https://user-images.githubusercontent.com/42051272/93665839-3ba1cd80-faac-11ea-89ff-58ef66da4638.png)
![bleunlock](https://user-images.githubusercontent.com/42051272/93665848-5bd18c80-faac-11ea-845c-e6a62facff73.png)

**Comment by ts1** [comment]
@VFiee Thanks for reporting!
On my Mac, it's displayed.
Maybe, if you pair your iPhone and Mac on Bluetooth Preference, it should be displayed.
I'll think about it some more.
Thanks anyway!

**Comment by VFiee** [comment]
> @VFiee Thanks for reporting!
> On my Mac, it's displayed.
> Maybe, if you pair your iPhone and Mac on Bluetooth Preference, it should be displayed.
> I'll think about it some more.
> Thanks anyway!

I just tried it again, first quit BleUnlock, then pair the Mac and iPhone, then open BleUnlock, the Bluetooth name is displayed correctly! But my Mac device bar shows two Iphone J, I don't know what this is!
![WechatIMG57](https://user-images.githubusercontent.com/42051272/93668260-de167c80-fabd-11ea-9a8e-bcc41d7bfaff.png)
![WechatIMG58](https://user-images.githubusercontent.com/42051272/93668265-e1aa0380-fabd-11ea-96a5-86a74cdfa16e.png)
![WechatIMG59](https://user-images.githubusercontent.com/42051272/93668266-e373c700-fabd-11ea-968b-1608ed8bcc14.png)

**Comment by ts1** [comment]
Thanks for the report.
I don't know why two devices are shown. Maybe it is safe to remove one (or both).
Anyways, I'll re-think the way to find the device.

**Comment by ts1** [comment]
At version 1.9.0, it displays Bluetooth name and MAC address if available.
I believe this fixed the issue.
Feel free to reopen if you have any problem
