### ISSUE TITLE
can't find my phone

### ISSUE THREAD

**Issue by wrx331** [ts1/BLEUnlock#18]
Thanks for your job! 
I can find my watch in the list , but I can't find my Huawei mate30 phone.

I have tried  this tool https://github.com/wzqcongcong/MacGuarder , it can detect my phone correctly . However,  it may crash when the screen is locked.

By the way, if my watch is connected with my phone, it can't be found either..

**Comment by ts1** [comment]
@wrx331 Your phone may be displayed as UUID (long hexadecimal number).
Put your phone as close as possible to the Mac and try the device with minimum dBm.
