### ISSUE TITLE
Long passwords seem to get truncated

### ISSUE THREAD

**Issue by hsjunn** [ts1/BLEUnlock#19]
It seems passwords are remembered up to 20 characters only. When my password was longer than that the app kept failing to log me in; it succeeded only after I had shortened mine.

If it's a design decision, I think you need to at least specify that in the readme.

**Comment by ts1** [comment]
Thanks for the report @hsjunn!
That is not the intended behavior. I will try to find out what is truncating the password.

**Comment by ts1** [comment]
This will be fixed in next release.
