### ISSUE TITLE
How about support more closer to unlock

### ISSUE THREAD

**Issue by AielloChan** [ts1/BLEUnlock#22]
<img width="344" alt="image" src="https://user-images.githubusercontent.com/7900765/96224082-92be9380-0fc1-11eb-91da-433d672d63e7.png">

For now, we just have `-50dBm`, the largest. How about more closer 😸

**Comment by ts1** [comment]
Thanks for the comment @AielloChan!
I'll change the maximum to -30dBm in the next release.
