### ISSUE TITLE
Move computer away from bluetooth device

### ISSUE THREAD

**Issue by AielloChan** [ts1/BLEUnlock#23]
Consider this situation: when I work in `room A`, it's close to my Bluetooth device (phone), and for some reason, I need to move my computer to `room B`, but I didn't take my Bluetooth device together. So my computer locked (It should not)

My solution:
So, how about just add an idle delay time (I don't know how to name it), when I move my computer, I still use it in a short time, so set a timeout for idle time.

**Comment by ts1** [comment]
This feature is released in [1.10.0](https://github.com/ts1/BLEUnlock/releases/tag/1.10.0).
