### ISSUE TITLE
add BLEUnlock to [home]brew?

### ISSUE THREAD

**Issue by maelcum** [ts1/BLEUnlock#27]
Hello.
This is not an issue, but a feature request. It would be awesome if BLEUnlock would be available via `brew install --cask bleunlock` in brew.sh.
Thank you for your attention.

**Comment by ts1** [comment]
Thanks for the input.
I do use Homebrew, but I don't know how it works, how to submit, etc.
It would certainly be nice to be able to install with brew.

**Comment by nkean** [comment]
They've got some good documentation for getting setup to contribute.
https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md

**Comment by joeyhoer** [comment]
Just made [a PR to homebrew-cask](https://github.com/Homebrew/homebrew-cask/pull/99912) for this.

**Comment by ts1** [comment]
@joeyhoer Thank you!

**Comment by joeyhoer** [comment]
This issue can be closed, as the PR was accepted into homebrew. 😄

**Comment by ts1** [comment]
Confirmed!
Thank you very much @joeyhoer!

**Comment by maelcum** [comment]
Thank you all for making this happen!!
