### ISSUE TITLE
not working in big sur 11.2.1

### ISSUE THREAD

**Issue by ShiOGong** [ts1/BLEUnlock#29]
:(

**Comment by ts1** [comment]
It's working on 11.2.1 for me.
Can you give me some more details?

**Comment by ShiOGong** [comment]
After upgrading to big sur 11.2.1 autofill not working even i set the password many times :(

**Comment by ts1** [comment]
Probably the same problem has occurred several times on my old MacBook Pro.
It rarely reproduces, though.
May I know what model you have?

**Comment by ShiOGong** [comment]
MacBook Pro 13inc 2016 4 Thunderbolt 3
when I deleted the keychain and added it again it worked
the delay is very serious (20s) but it worked
i think the problem is solved thank you for your patience
