### ISSUE TITLE
Get notified on iPhone/iWatch when mac is locked/unlocked

### ISSUE THREAD

**Issue by wenmin-wu** [ts1/BLEUnlock#3]
Hi, this project is quite useful. However I’m still wondering is it possible to get notified on iPhone/iWatch when mac is locked/unlocked.

**Comment by ts1** [comment]
Hi @wenmin-wu 
Unfortunately that feature requires a companion app on iPhone/Watch side.
And creating iPhone/Watch app is beyond this project at the moment.

**Comment by wenmin-wu** [comment]
@ts1 ok, I see, thanks. By the way, is there any way to get the device name like "William's iPhone". The shown device name while scanning is hard to recognize which one is mine.

**Comment by ts1** [comment]
That information is not accessible through the official API of macOS.
Maybe it is hidden for privacy.
I'd like to know if someone knows how.

**Comment by nightwallaby** [comment]
@wenmin-wu I use the script to send a Pushover notification to my phone which works well.
