### ISSUE TITLE
Stuck on scanning

### ISSUE THREAD

**Issue by nemesis911** [ts1/BLEUnlock#32]
I am unable to find a device, it just says scanning constantly. I'm on osx 10.13.6. Would there be anyway to fix this or is there anything i can run in the terminal to make this work?

Thanks in advance.

**Comment by ts1** [comment]
I'm not sure what is happening.
What is your BLE device?

**Comment by nemesis911** [comment]
Macbook Pro 2011

**Comment by ts1** [comment]
It seems MacBook Pro 2011 does not support Bluetooth LE (Bluetooth >= 4.0).
https://support.apple.com/kb/SP645
