### ISSUE TITLE
mac 电脑安装之后无法彻底卸载?

### ISSUE THREAD

**Issue by hmlSunshine** [ts1/BLEUnlock#34]
安装之后开启开机自启动,退出软件,移动到废纸篓,并且清空废纸篓,然后重启,软件开机启动了,然后 app 早清除了,很迷惑,有什么办法彻底卸载吗,清空废纸篓后解压又点了一次,怎么感觉好像安装了两个,求彻底卸载方法

**Comment by ts1** [comment]
If it boots, it must be in somewhere in your Mac.
While the app is running, open Terminal.app and type the command below, it will show the path.
```
ps aux | grep BLEUnlock
```
