### ISSUE TITLE
Failed to get Bluetooth device list

### ISSUE THREAD

**Issue by wqq578** [ts1/BLEUnlock#45]

**Comment by ts1** [comment]
Please let me know the details such as OS version.

**Comment by wqq578** [comment]
> Please let me know the details such as OS version.

10.15.7
The first installation will do.
Re-install do not know what the authorization, it seems to point the wrong authorization
After that, the Bluetooth list is not displayed

**Comment by ts1** [comment]
Is there Bluetooth in System Preferences > Security & Privacy > Privacy?
(I'm not sure if Catalina has it)
If it is there, make sure BLEUnlock is turned on.

**Comment by wqq578** [comment]
> Is there Bluetooth in System Preferences > Security & Privacy > Privacy?
> (I'm not sure if Catalina has it)
> If it is there, make sure BLEUnlock is turned on.

Is there Bluetooth in System Preferences > Security & Privacy > Privacy?
NO

**Comment by wqq578** [comment]
![image](https://user-images.githubusercontent.com/47521670/127152900-46033346-8288-42e4-826b-7bc4fd8ed35a.png)

**Comment by wqq578** [comment]
![image](https://user-images.githubusercontent.com/47521670/127153460-b7d51c45-333e-4ade-8859-bd896359ebe7.png)

**Comment by ts1** [comment]
Sorry, but I don't know what's going on.
Please try the following:
1. Reset the Bluetooth module (Option+Shift+click on the Bluetooth icon in the menu bar).
2. Reset SMC.
3. Reset NVRAM.
4. Remove `/Library/Preferences/com.apple.Bluetooth.plist` in recovery mode (pairing information etc. may be lost).

**Comment by nigolarer** [comment]
i ve facing the same issue after i reboot my mac(M1). i ve already permitted Bluetooh to BLUnlock and assistant.

**Comment by wqq578** [comment]
> 



> i ve facing the same issue after i reboot my mac(M1). i ve already permitted Bluetooh to BLUnlock and assistant.

**Comment by wqq578** [comment]
> i ve facing the same issue after i reboot my mac(M1). i ve already permitted Bluetooh to BLUnlock and assistant.

It's been settled
Two schemes were tried
1 brew Uninstalling software
2 Use other cleaning software to completely uninstall and reinstall

**Comment by nigolarer** [comment]
> 



> > i ve facing the same issue after i reboot my mac(M1). i ve already permitted Bluetooh to BLUnlock and assistant.
> 
> It's been settled Two schemes were tried 1 brew Uninstalling software 2 Use other cleaning software to completely uninstall and reinstall

Thx for ur reply, but after un&reinstall and clean up by some tmp file cleaner app, this problem still unresolved. Could u plz offer config or tmp file directory that this app will write to? Thx a lot, this app really give me such a big convenience.

**Comment by wqq578** [comment]
> > 
> 
> > > i ve facing the same issue after i reboot my mac(M1). i ve already permitted Bluetooh to BLUnlock and assistant.
> > 
> > 
> > It's been settled Two schemes were tried 1 brew Uninstalling software 2 Use other cleaning software to completely uninstall and reinstall
> 
> Thx for ur reply, but after un&reinstall and clean up by some tmp file cleaner app, this problem still unresolved. Could u plz offer config or tmp file directory that this app will write to? Thx a lot, this app really give me such a big convenience.

You can add my contact information wqq578. I used the third-party software to uninstall it

**Comment by wqq578** [comment]
I remember uninstalling it using ‘CleanMyMac X’, the free version. Uninstall finished, I also cleaned up the software

**Comment by nigolarer** [comment]
> I remember uninstalling it using ‘CleanMyMac X’, the free version. Uninstall finished, I also cleaned up the software

thx a lot, this clean app literally worked and BLEUnlock on my mac well as before now :)
FYI: Though `CleanMyMac X` free version have soooo  many limits, it shows app and related file path clearly and can easy to remove manually by oneself.
