### ISSUE TITLE
Unlocking without change in proximity

### ISSUE THREAD

**Issue by vin047** [ts1/BLEUnlock#54]
Hey, is it possible to unlock without requiring a change in proximity? For example if you lock your device manually by starting screensaver but then change your mind and decide to unlock right away.

**Comment by ts1** [comment]
The way I do it is to use the standard Mac method (Control + Shift + Eject) to sleep (lock) the screen, and hit any key to wake it up (unlock by BLEUnlock).

**Comment by vin047** [comment]
Thanks, that does seem to work just fine. Closing this issue.
