### ISSUE TITLE
BLEUnlock only works in Monterey B7 when the Mac is restarted.

### ISSUE THREAD

**Issue by etrahretep** [ts1/BLEUnlock#56]
BLEUnlock only works in Monterey B7 when the Mac is restarted.
When logout/login the app is inactive and doesn't scan.

12.0 bèta (21A5522h)
Mac (Retina 5K, 27-inch, Late 2015)

**Comment by ts1** [comment]
Confirmed.
It's a strange behavior, but I'll see if I can work around it.

**Comment by etrahretep** [comment]
Same behavior in B8...

**Comment by ts1** [comment]
This is just a workaround, but restarting `bluetoothd` enables BLEUnlock again.

```
ts1@monterey ~ % sudo pkill bluetoothd
```

**Comment by etrahretep** [comment]
Thanks for the workaround. Hope you find a easier solution.

**Comment by etrahretep** [comment]
Same behavior in B9...

**Comment by etrahretep** [comment]
Yes, I noticed. Thanks!
