### ISSUE TITLE
Can I disable auto lock?

### ISSUE THREAD

**Issue by yueziii** [ts1/BLEUnlock#6]
Hi, this project is wonderful. However I’m wondring  can i disable auto lock function but only enable auto unlock? Thanks.

**Comment by ts1** [comment]
@yueziii Thanks for the suggestion!
I'll add that feature some time soon.

**Comment by yueziii** [comment]
@ts1 Thanks a lot!

**Comment by ts1** [comment]
Added 'Disable' option in Lock RSSI menu.

**Comment by timmerk** [comment]
Any chance you could add a Disable option in the Unlock RSSI menu, too? Thanks!

**Comment by ts1** [comment]
@timmerk Sure, I'll add it when I have time.
