### ISSUE TITLE
os12 often fails to connect to Bluetooth

### ISSUE THREAD

**Issue by backy-1451592168** [ts1/BLEUnlock#69]
You need to restart before the software can connect to Bluetooth

**Comment by ts1** [comment]
Yes, Monterey Yes, Monterey got a lot of bugs with Bluetooth.
My BT earphones cut out a lot more often than the previous OS.
Plus, you can't reset it from the menu anymore.
To reset it, you need to run `sudo pkill bluetoothd`.

There is nothing I can do as an app developer, I can only hope that the OS will be fixed.
